version: 0.2
phases:
  build:
    commands:
      - |
        echo Build started on `date`
        filename="sample_config_file.txt"
        file=$CODEBUILD_SRC_DIR/config_files/"${filename}"
        echo $file
        echo Printing env variables
        echo "${env}"
        echo "${domain}"
        KEY="${domain}_${env}"
        echo "${KEY}"
        VALUE=$(grep "^${KEY}=" "$file" | sed -e "s/^${KEY}=//")
        if [ -z "$VALUE" ]; then
        echo "Key '$KEY' not found in $file"
        else echo "The value for '$KEY' is '$VALUE'"
        fi
        cfnfilename="main.yaml"
        cfnfile=$CODEBUILD_SRC_DIR/cfn/"${cfnfilename}"
        echo $cfnfile
        bucketfilename="bucket.yaml"
        bucketfile=$CODEBUILD_SRC_DIR/cfn/"${bucketfilename}"
        echo $bucketfile
        dbresourcelinkfilename="glue_resourcelink.yaml"
        dbresourcelinkfile=$CODEBUILD_SRC_DIR/cfn/"${dbresourcelinkfilename}"
        echo $dbresourcelinkfile
        lffilename="LakeFormation.yaml"
        lffile=$CODEBUILD_SRC_DIR/cfn/"${lffilename}"
        echo $lffile
        aws s3 cp $bucketfile s3://producer-mycicd-bucket-ap/cicd-files/
        aws s3 cp $dbresourcelinkfile s3://producer-mycicd-bucket-ap/cicd-files/
        aws s3 cp $lffile s3://producer-mycicd-bucket-ap/cicd-files/      
        bucketurl=https://s3.amazonaws.com/producer-mycicd-bucket-ap/cicd-files/bucket.yaml
        dbresourcelinkurl=https://s3.amazonaws.com/producer-mycicd-bucket-ap/cicd-files/glue_resourcelink.yaml  
        lfurl=https://s3.amazonaws.com/producer-mycicd-bucket-ap/cicd-files/LakeFormation.yaml       
        aws cloudformation deploy \
          --template-file $cfnfile \
          --stack-name datamesh-stack \
          --parameter-overrides EnvType="${env}" DomainName="${domain}" BucketFilePath="${bucketurl}" ResourcelinkPath="${dbresourcelinkurl}" lfPath="${lfurl}" \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
  post_build:
    commands:
      - aws cloudformation describe-stack-events --stack-name datamesh-stack
      - echo Build complete